services:
  # Backend Service (FastAPI)
  - type: web
    name: llm-drift-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python init_db.py && uvicorn main:app --host 0.0.0.0 --port 8000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9

  # Frontend Service (Next.js)
  - type: web
    name: llm-drift-frontend
    runtime: node
    plan: free
    rootDir: .
    buildCommand: "npm install && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NEXT_PUBLIC_API_URL
        value: https://llm-drift-backend.onrender.com
